### ISSUE TITLE
Plugin not loading existing missions

### ISSUE THREAD

**Issue by jberanek** [lunarplasma/EDMC-CombatTracker#1]
Plugin version 0.1.0

I have a few massacre missions currently, but when EDMC starts up the plugin display is there, but shows no mission data.

Relevant looking bit of data from the logs:

```
2021-02-17 10:25:55.949 - INFO - <plugins>.EDMC-CombatTracker-0.1.0.controller.Controller.rebuild_from_logs:38: Starting to read previous journal files: C:\Users\john\AppData\Local\EDMarketConnector\plugins\EDMC-CombatTracker-0.1.0\Test\Data
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "C:\Users\john\AppData\Local\EDMarketConnector\plugins\EDMC-CombatTracker-0.1.0\controller.py", line 40, in rebuild_from_logs
    logs = [f for f in os.listdir(journal_folder) if ".log" in f]  # get logs only
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\john\\AppData\\Local\\EDMarketConnector\\plugins\\EDMC-CombatTracker-0.1.0\\Test\\Data'
```

**Comment by jberanek** [comment]
Full log file at https://gist.github.com/86a82f5664e04dd1bc36933fea6b102c

**Comment by lunarplasma** [comment]
I see what the error is there - some test code got inadvertently committed. I'll upload a new release shortly.

**Comment by pa-jberanek** [comment]
I can indeed see it :)

**Comment by lunarplasma** [comment]
Release made: https://github.com/lunarplasma/EDMC-CombatTracker/releases/tag/0.1.1

**Comment by jberanek** [comment]
OK, after installing that (and fixing the version specifier https://github.com/lunarplasma/EDMC-CombatTracker/pull/2 ) I get:

```
C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210216210754.01.log 2413 { "timestamp":"2021-02-16T23:22:13Z", "event":"MissionCompleted", "Faction":"Hai Ho Silver Linings", "Name":"Mission_MassacreWing_name", "MissionID":711231433, "TargetType":"$MissionUtil_FactionTag_Pirate;", "TargetType_Localised":"Pirates", "TargetFaction":"LHS 1358 Jet Gang", "KillCount":45, "NewDestinationSystem":"Inti", "DestinationSystem":"LHS 1358", "NewDestinationStation":"Reiter Ring", "DestinationStation":"Davy Beacon", "Reward":21629820, "FactionEffects":[ { "Faction":"Hai Ho Silver Linings", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[  ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"LHS 1358 Jet Gang", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":5068732376473, "Trend":"DownBad", "Influence":"+" } ], "ReputationTrend":"DownBad", "Reputation":"+" } ] }
 <class 'ValueError'> list.remove(x): x not in list
```

The plugin shows the first pending mission, but the other 4 are not shown.

**Comment by jberanek** [comment]
https://i.imgur.com/Ai9SX7L.png

**Comment by jberanek** [comment]
More complete log:
```
2021-02-17 12:44:39.907 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:38: Starting to read previous journal files: C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous
2021-02-17 12:44:39.909 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210215145226.01.log
2021-02-17 12:44:39.913 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210215192245.01.log
2021-02-17 12:44:39.953 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210216083558.01.log
2021-02-17 12:44:39.961 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210216165541.01.log
2021-02-17 12:44:39.975 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210216210754.01.log
C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210216210754.01.log 2413 { "timestamp":"2021-02-16T23:22:13Z", "event":"MissionCompleted", "Faction":"Hai Ho Silver Linings", "Name":"Mission_MassacreWing_name", "MissionID":711231433, "TargetType":"$MissionUtil_FactionTag_Pirate;", "TargetType_Localised":"Pirates", "TargetFaction":"LHS 1358 Jet Gang", "KillCount":45, "NewDestinationSystem":"Inti", "DestinationSystem":"LHS 1358", "NewDestinationStation":"Reiter Ring", "DestinationStation":"Davy Beacon", "Reward":21629820, "FactionEffects":[ { "Faction":"Hai Ho Silver Linings", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[  ], "ReputationTrend":"UpGood", "Reputation":"++" }, { "Faction":"LHS 1358 Jet Gang", "Effects":[ { "Effect":"$MISSIONUTIL_Interaction_Summary_EP_up;", "Effect_Localised":"The economic status of $#MinorFaction; has improved in the $#System; system.", "Trend":"UpGood" } ], "Influence":[ { "SystemAddress":5068732376473, "Trend":"DownBad", "Influence":"+" } ], "ReputationTrend":"DownBad", "Reputation":"+" } ] }
 <class 'ValueError'> list.remove(x): x not in list
2021-02-17 12:44:40.004 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210217081554.01.log
2021-02-17 12:44:40.013 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:47: Reading C:\Users\john\Saved Games\Frontier Developments\Elite Dangerous\Journal.210217102703.01.log
2021-02-17 12:44:40.023 - INFO - <plugins>.EDMC-CombatTracker-0.1.1.controller.Controller.rebuild_from_logs:62: Finished reading journals.
```

**Comment by lunarplasma** [comment]
I've pushed a commit to the [main branch](https://github.com/lunarplasma/EDMC-CombatTracker/commit/07efda5863ce9dfc3b822e618fad63863b3f068b). Improved the logging when rebuilding from logs, and also added a membership check which should prevent that error.

**Comment by jberanek** [comment]
This fixed it for me:
```
            try:
                ids.remove(mission_id)
            except:
                logger.info(f"Didn't know about mission ID {mission_id} - oh well")
```

**Comment by jberanek** [comment]
Well, apart from I've not understood Python exception handling properly, so the exception still spams the log...

**Comment by lunarplasma** [comment]
> This fixed it for me:
> 
> ```
>             try:
>                 ids.remove(mission_id)
>             except:
>                 logger.info(f"Didn't know about mission ID {mission_id} - oh well")
> ```

Yeah, that's fine. The last commit I made to `main` has a dodge mechanism so it would amount to the same.

**Comment by lunarplasma** [comment]
> Well, apart from I've not understood Python exception handling properly, so the exception still spams the log...

How much was it spamming the log? I had thought this was a corner case (where a MissionComplete is read, without having had a MissionAccepted event having been read beforehand).

**Comment by jberanek** [comment]
> > Well, apart from I've not understood Python exception handling properly, so the exception still spams the log...
> 
> How much was it spamming the log? I had thought this was a corner case (where a MissionComplete is read, without having had a MissionAccepted event having been read beforehand).

Sorry, it was only spamming the log as the logging statement in the exception handling caused an exception itself, as logging in massacres.py was broken, because of it being in a subdir, fixed with:

```
plugin_name = os.path.basename(os.path.normpath(os.path.join(os.path.dirname(__file__), '..')))
logger = logging.getLogger(f"{appname}.{plugin_name}")
```

and exception improved to:

```
            try:
                ids.remove(mission_id)
            except ValueError:
                logger.info(f"Didn't know about mission ID {mission_id} - oh well")
                pass
```

**Comment by lunarplasma** [comment]
Oh, do you have it in a sub-subdir? 

Should be in: plugins > EDMC-CombatTracker/<load.py and other files in here>

**Comment by jberanek** [comment]
I mean the "Data" subdir in the plugin, where massacres.py lives.

**Comment by lunarplasma** [comment]
Marking this as closed. New issues can be raised if there are still problems found.
